USE	QuanLyCuaHangBanSach
GO

ALTER TABLE HoaDon ADD FOREIGN KEY(KhachHang) REFERENCES KhachHang(SDT_KH)
GO

ALTER TABLE ChiTietHoaDon ADD FOREIGN KEY (HoaDon) REFERENCES HoaDon(MaHD)
GO
ALTER TABLE ChiTietHoaDon ADD FOREIGN KEY (MaSachMua) REFERENCES Sach(MaSach)
GO

ALTER TABLE ChiTietPhieuNhap ADD FOREIGN KEY (PhieuNhap) REFERENCES PhieuNhapSach(MaPN)
GO
ALTER TABLE ChiTietPhieuNhap ADD FOREIGN KEY (MaSachNhap) REFERENCES Sach(MaSach)
GO 