//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhap
    {
        public int PhieuNhap { get; set; }
        public string MaSachNhap { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal GiaTienNhap { get; set; }
        public decimal TongTien { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual PhieuNhapSach PhieuNhapSach { get; set; }
    }
}
