//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string KhachHang { get; set; }
        public bool HinhThucThanhToan { get; set; }
        public decimal TongGiaTriHD { get; set; }
    }
}
