
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PhanMemBanSach
{

using System;
    using System.Collections.Generic;
    
public partial class PhieuNhapSach
{

    public int MaPN { get; set; }

    public System.DateTime NgayNhap { get; set; }

    public decimal TongGiaTriNhap { get; set; }

}

}
