//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeQuy
    {
        public short Quy { get; set; }
        public short Nam { get; set; }
        public decimal DoanhThu { get; set; }
        public decimal TongChiTieu { get; set; }
        public decimal LoiNhuan { get; set; }
    }
}
